spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/survey_db
spring.datasource.username=sakamototaiki
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
