name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        # リポジトリルートから見てfrontendフォルダへ移動して実行
        run: npm install
        working-directory: frontend

      - name: Build
        # リポジトリルートから見てfrontendフォルダでビルド
        run: npm run build
        working-directory: frontend

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # ビルド結果(out)がfrontendフォルダの中にある前提
          path: frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
